//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CuratorJournal.DataAccess.DTOs
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClassHourDTO
    {
    
        public int ClassHourId { get; set; }
        public System.DateTime Date { get; set; }
        public string Topic { get; set; }
        public string Decision { get; set; }
    }
}
