//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CuratorJournal.DataAccess.DTOs
{
    using System;
    using System.Collections.Generic;
    
    public partial class SocialStatuDTO
    {
    
        public int SocialStatusId { get; set; }
        public string Name { get; set; }
    }
}
