//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CuratorJournal.DataAccess.DTOs
{
    
    public partial class StudentDTO
    {
    
        public int StudentId { get; set; }
        public bool IsDeduction { get; set; }
        public System.DateTime DateDeduction { get; set; }
    }
}
