//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CuratorJournal.Frameworks.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClassHour
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ClassHour()
        {
            this.StudentClassHours = new HashSet<StudentClassHour>();
        }
    
        public int ClassHourId { get; set; }
        public System.DateTime Date { get; set; }
        public string Topic { get; set; }
        public string Decision { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentClassHour> StudentClassHours { get; set; }
    }
}
