//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CuratorJournal.Frameworks.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParentMeeting
    {
        public int MeetingId { get; set; }
        public int StudyGroupId { get; set; }
        public int Visited { get; set; }
        public int NotVisitedWithReason { get; set; }
        public int NotVisited { get; set; }
        public string Topic { get; set; }
        public string Decision { get; set; }
    
        public virtual StudyGroup StudyGroup { get; set; }
    }
}
