//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CuratorJournal.Frameworks.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentInDormitory
    {
        public int StudentId { get; set; }
        public int Room { get; set; }
    
        public virtual Student Student { get; set; }
    }
}
