//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CuratorJournal.Desktop.DTOs
{
    using System;
    using System.Collections.Generic;
    
    public partial class CuratorDTO
    {
    
        public int CuratorId { get; set; }
        public int PersonId { get; set; }
        public int CategoryId { get; set; }
        public int UserId { get; set; }
    }
}
