//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CuratorJournal.Desktop.DTOs
{
    using System;
    using System.Collections.Generic;
    
    public partial class IndividualWorkDTO
    {
        public int IndividualWorkId { get; set; }
        public bool IsStudent { get; set; }
        public int StudentId { get; set; }
        public int ParentId { get; set; }
        public string Topic { get; set; }
        public string Decision { get; set; }
        public System.DateTime Date { get; set; }
    }
}
