//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CuratorJournal.Desktop.DTOs
{
    
    public partial class StudentClassHourDTO
    {
        public int ClassHourId { get; set; }
        public int StudentId { get; set; }
        public bool IsVisited { get; set; }
    }
}
