//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CuratorJournal.DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CuratorJournalEntities : DbContext
    {
        public CuratorJournalEntities()
            : base("name=CuratorJournalEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ClassHour> ClassHours { get; set; }
        public virtual DbSet<Curator> Curators { get; set; }
        public virtual DbSet<CuratorCharacteristic> CuratorCharacteristics { get; set; }
        public virtual DbSet<Direction> Directions { get; set; }
        public virtual DbSet<GroupPost> GroupPosts { get; set; }
        public virtual DbSet<Hobby> Hobbies { get; set; }
        public virtual DbSet<IndividualWork> IndividualWorks { get; set; }
        public virtual DbSet<Parent> Parents { get; set; }
        public virtual DbSet<ParentMeeting> ParentMeetings { get; set; }
        public virtual DbSet<Person> People { get; set; }
        public virtual DbSet<SocialStatu> SocialStatus { get; set; }
        public virtual DbSet<Specialization> Specializations { get; set; }
        public virtual DbSet<Student> Students { get; set; }
        public virtual DbSet<StudentClassHour> StudentClassHours { get; set; }
        public virtual DbSet<StudentInDormitory> StudentInDormitories { get; set; }
        public virtual DbSet<StudyGroup> StudyGroups { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TeacherCategory> TeacherCategories { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
