//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CuratorJournal.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CuratorCharacteristic
    {
        public int CharacteristicId { get; set; }
        public int StudentId { get; set; }
        public int CuratorId { get; set; }
        public string Characteristic { get; set; }
        public System.DateTime DateCreated { get; set; }
    
        public virtual Curator Curator { get; set; }
        public virtual Student Student { get; set; }
    }
}
